name: build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: with jdk ${{ matrix.java }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11', '16' ]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Build with Maven
        run: ./mvnw --no-transfer-progress clean verify

  sonar:
    name: sonar analyse
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run SonarCloud analyse
        run: >
          ./mvnw --batch-mode --no-transfer-progress clean
          org.jacoco:jacoco-maven-plugin:prepare-agent verify
          org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=michael-simons-github
          -Dsonar.projectKey=eu.michael-simons:wro4j-spring-boot-starter
          -Dsonar.branch.name=${GITHUB_REF##*/}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
